insert into c_credentials(system_code,system_key) values('TNDP1','bearer f8dccd339263afe65615d96e9aa5e3c067cd62798a79af0f51dea345b35b5bd2')
insert into c_credentials(system_code,system_key) values('RVLP1','1b602ba1ed114c609a8ac95443bd7955:caa245662e1f406685dfcbbcb8554e054579f10b6fae45678630e4beb2f3cfe4')

insert into c_environment(system_name,description,refcode,flag) values('Revel','Development','RVLD1',      0 )
insert into c_environment(system_name,description,refcode,flag) values('Revel','Development','RVLD2',      0 )
insert into c_environment(system_name,description,refcode,flag) values('Revel','SIT','RVLS1',      0 )
insert into c_environment(system_name,description,refcode,flag) values('Revel','UAT','RVLU1',      0 )
insert into c_environment(system_name,description,refcode,flag) values('Revel','Preproduction','RVLV1',      0 )
insert into c_environment(system_name,description,refcode,flag) values('Revel','Production','RVLP1',      1 )
insert into c_environment(system_name,description,refcode,flag) values('Revel','Live','RVLL1',      0 )
insert into c_environment(system_name,description,refcode,flag) values('Tanda','Development','TNDD1',      0 )
insert into c_environment(system_name,description,refcode,flag) values('Tanda','Development','TNDD2',      0 )
insert into c_environment(system_name,description,refcode,flag) values('Tanda','SIT','TNDS1',      0 )
insert into c_environment(system_name,description,refcode,flag) values('Tanda','UAT','TNDU1',      0 )
insert into c_environment(system_name,description,refcode,flag) values('Tanda','Preproduction','TNDV1',      0 )
insert into c_environment(system_name,description,refcode,flag) values('Tanda','Production','TNDP1',      1 )
insert into c_environment(system_name,description,refcode,flag) values('Tanda','Live','TNDL1',      0 )